#!/bin/bash 

#source <(curl https://raw.githubusercontent.com/jkool702/forkrun/main/forkrun.bash)
source '/home/liveuser/forkrun.new.bash'

mkdir -p /mnt/ramdisk
cat /proc/mounts | grep -F '/mnt/ramdisk' || mount -t tmpfs tmpfs /mnt/ramdisk

rsync -a /usr /mnt/ramdisk
which nproc 1>/dev/null 2>/dev/null && nProcs=$(nproc) || nProcs=4

#mapfile -t A0 < <(find /mnt/ramdisk -type f | head -n $(( ${nProcs} * 1024 )))
mapfile -t A0 < <(find /mnt/ramdisk -type f | head -n $(( ${nProcs} * 1024 )))
mapfile -t A1 < <(printf '%s\n' "${A0[@]}" | head -n $(( ${nProcs} * 128 )))
mapfile -t A2 < <(printf '%s\n' "${A1[@]}" | head -n  $(( ${nProcs} + 2 )))
mapfile -t A3 < <(printf '%s\n' "${A2[@]}" | head -n  $(( ${nProcs} - 2 )))

nMax=16

for nn in A3 A2 A1 A0; do
declare -n C="$nn"

nMax="$(( $nMax / 2 ))"

echo "BEGINNING TEST CASE FOR STDIN LENGTH = ${#C[@]}"


{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks sha1sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks sha1sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks sha256sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks sha256sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks printf '%s\n') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks printf '"'"'%s\n'"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -- sha1sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -- sha1sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -- sha256sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -- sha256sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -- printf '%s\n') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -- printf '"'"'%s\n'"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -i sha1sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -i sha1sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -i sha256sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -i sha256sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -i printf '%s\n' {}) <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -i printf '"'"'%s\n'"'"' {}'; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -i -- sha1sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -i -- sha1sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -i -- sha256sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -i -- sha256sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -i -- printf '%s\n' {}) <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -i -- printf '"'"'%s\n'"'"' {}'; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -d 3 sha1sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -d 3 sha1sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -d 3 sha256sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -d 3 sha256sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -d 3 printf '%s\n') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -d 3 printf '"'"'%s\n'"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -d 3 -- sha1sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -d 3 -- sha1sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -d 3 -- sha256sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -d 3 -- sha256sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -d 3 -- printf '%s\n') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -d 3 -- printf '"'"'%s\n'"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -d 3 -i sha1sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -d 3 -i sha1sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -d 3 -i sha256sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -d 3 -i sha256sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -d 3 -i printf '%s\n' {}) <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -d 3 -i printf '"'"'%s\n'"'"' {}'; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -d 3 -i -- sha1sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -d 3 -i -- sha1sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -d 3 -i -- sha256sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -d 3 -i -- sha256sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -d 3 -i -- printf '%s\n' {}) <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -d 3 -i -- printf '"'"'%s\n'"'"' {}'; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp sha1sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp sha1sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp sha256sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp sha256sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp printf '%s\n') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp printf '"'"'%s\n'"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -- sha1sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -- sha1sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -- sha256sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -- sha256sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -- printf '%s\n') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -- printf '"'"'%s\n'"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -i sha1sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -i sha1sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -i sha256sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -i sha256sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -i printf '%s\n' {}) <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -i printf '"'"'%s\n'"'"' {}'; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -i -- sha1sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -i -- sha1sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -i -- sha256sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -i -- sha256sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -i -- printf '%s\n' {}) <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -i -- printf '"'"'%s\n'"'"' {}'; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -d 3 sha1sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -d 3 sha1sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -d 3 sha256sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -d 3 sha256sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -d 3 printf '%s\n') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -d 3 printf '"'"'%s\n'"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -d 3 -- sha1sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -d 3 -- sha1sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -d 3 -- sha256sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -d 3 -- sha256sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -d 3 -- printf '%s\n') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -d 3 -- printf '"'"'%s\n'"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -d 3 -i sha1sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -d 3 -i sha1sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -d 3 -i sha256sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -d 3 -i sha256sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -d 3 -i printf '%s\n' {}) <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -d 3 -i printf '"'"'%s\n'"'"' {}'; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -d 3 -i -- sha1sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -d 3 -i -- sha1sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -d 3 -i -- sha256sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -d 3 -i -- sha256sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -d 3 -i -- printf '%s\n' {}) <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -t /tmp -d 3 -i -- printf '"'"'%s\n'"'"' {}'; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 sha1sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 sha1sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 sha256sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 sha256sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 printf '%s\n') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 printf '"'"'%s\n'"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -- sha1sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -- sha1sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -- sha256sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -- sha256sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -- printf '%s\n') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -- printf '"'"'%s\n'"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -i sha1sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -i sha1sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -i sha256sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -i sha256sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -i printf '%s\n' {}) <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -i printf '"'"'%s\n'"'"' {}'; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -i -- sha1sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -i -- sha1sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -i -- sha256sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -i -- sha256sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -i -- printf '%s\n' {}) <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -i -- printf '"'"'%s\n'"'"' {}'; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -d 3 sha1sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -d 3 sha1sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -d 3 sha256sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -d 3 sha256sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -d 3 printf '%s\n') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -d 3 printf '"'"'%s\n'"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -d 3 -- sha1sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -d 3 -- sha1sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -d 3 -- sha256sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -d 3 -- sha256sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -d 3 -- printf '%s\n') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -d 3 -- printf '"'"'%s\n'"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -d 3 -i sha1sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -d 3 -i sha1sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -d 3 -i sha256sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -d 3 -i sha256sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -d 3 -i printf '%s\n' {}) <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -d 3 -i printf '"'"'%s\n'"'"' {}'; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -d 3 -i -- sha1sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -d 3 -i -- sha1sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -d 3 -i -- sha256sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -d 3 -i -- sha256sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -d 3 -i -- printf '%s\n' {}) <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -d 3 -i -- printf '"'"'%s\n'"'"' {}'; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp sha1sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp sha1sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp sha256sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp sha256sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp printf '%s\n') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp printf '"'"'%s\n'"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -- sha1sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -- sha1sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -- sha256sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -- sha256sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -- printf '%s\n') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -- printf '"'"'%s\n'"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -i sha1sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -i sha1sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -i sha256sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -i sha256sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -i printf '%s\n' {}) <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -i printf '"'"'%s\n'"'"' {}'; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -i -- sha1sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -i -- sha1sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -i -- sha256sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -i -- sha256sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -i -- printf '%s\n' {}) <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -i -- printf '"'"'%s\n'"'"' {}'; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -d 3 sha1sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -d 3 sha1sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -d 3 sha256sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -d 3 sha256sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -d 3 printf '%s\n') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -d 3 printf '"'"'%s\n'"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -d 3 -- sha1sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -d 3 -- sha1sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -d 3 -- sha256sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -d 3 -- sha256sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -d 3 -- printf '%s\n') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -d 3 -- printf '"'"'%s\n'"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -d 3 -i sha1sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -d 3 -i sha1sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -d 3 -i sha256sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -d 3 -i sha256sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -d 3 -i printf '%s\n' {}) <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -d 3 -i printf '"'"'%s\n'"'"' {}'; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -d 3 -i -- sha1sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -d 3 -i -- sha1sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -d 3 -i -- sha256sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -d 3 -i -- sha256sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -d 3 -i -- printf '%s\n' {}) <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -l 1 -t /tmp -d 3 -i -- printf '"'"'%s\n'"'"' {}'; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 sha1sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 sha1sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 sha256sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 sha256sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 printf '%s\n') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 printf '"'"'%s\n'"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -- sha1sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -- sha1sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -- sha256sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -- sha256sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -- printf '%s\n') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -- printf '"'"'%s\n'"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -i sha1sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -i sha1sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -i sha256sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -i sha256sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -i printf '%s\n' {}) <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -i printf '"'"'%s\n'"'"' {}'; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -i -- sha1sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -i -- sha1sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -i -- sha256sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -i -- sha256sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -i -- printf '%s\n' {}) <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -i -- printf '"'"'%s\n'"'"' {}'; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -d 3 sha1sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -d 3 sha1sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -d 3 sha256sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -d 3 sha256sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -d 3 printf '%s\n') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -d 3 printf '"'"'%s\n'"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -d 3 -- sha1sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -d 3 -- sha1sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -d 3 -- sha256sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -d 3 -- sha256sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -d 3 -- printf '%s\n') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -d 3 -- printf '"'"'%s\n'"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -d 3 -i sha1sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -d 3 -i sha1sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -d 3 -i sha256sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -d 3 -i sha256sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -d 3 -i printf '%s\n' {}) <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -d 3 -i printf '"'"'%s\n'"'"' {}'; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -d 3 -i -- sha1sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -d 3 -i -- sha1sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -d 3 -i -- sha256sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -d 3 -i -- sha256sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -d 3 -i -- printf '%s\n' {}) <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -d 3 -i -- printf '"'"'%s\n'"'"' {}'; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp sha1sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp sha1sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp sha256sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp sha256sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp printf '%s\n') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp printf '"'"'%s\n'"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -- sha1sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -- sha1sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -- sha256sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -- sha256sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -- printf '%s\n') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -- printf '"'"'%s\n'"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -i sha1sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -i sha1sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -i sha256sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -i sha256sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -i printf '%s\n' {}) <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -i printf '"'"'%s\n'"'"' {}'; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -i -- sha1sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -i -- sha1sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -i -- sha256sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -i -- sha256sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -i -- printf '%s\n' {}) <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -i -- printf '"'"'%s\n'"'"' {}'; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -d 3 sha1sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -d 3 sha1sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -d 3 sha256sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -d 3 sha256sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -d 3 printf '%s\n') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -d 3 printf '"'"'%s\n'"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -d 3 -- sha1sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -d 3 -- sha1sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -d 3 -- sha256sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -d 3 -- sha256sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -d 3 -- printf '%s\n') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -d 3 -- printf '"'"'%s\n'"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -d 3 -i sha1sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -d 3 -i sha1sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -d 3 -i sha256sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -d 3 -i sha256sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -d 3 -i printf '%s\n' {}) <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -d 3 -i printf '"'"'%s\n'"'"' {}'; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -d 3 -i -- sha1sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -d 3 -i -- sha1sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -d 3 -i -- sha256sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -d 3 -i -- sha256sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -d 3 -i -- printf '%s\n' {}) <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -t /tmp -d 3 -i -- printf '"'"'%s\n'"'"' {}'; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 sha1sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 sha1sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 sha256sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 sha256sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 printf '%s\n') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 printf '"'"'%s\n'"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -- sha1sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -- sha1sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -- sha256sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -- sha256sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -- printf '%s\n') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -- printf '"'"'%s\n'"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -i sha1sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -i sha1sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -i sha256sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -i sha256sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -i printf '%s\n' {}) <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -i printf '"'"'%s\n'"'"' {}'; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -i -- sha1sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -i -- sha1sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -i -- sha256sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -i -- sha256sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -i -- printf '%s\n' {}) <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -i -- printf '"'"'%s\n'"'"' {}'; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -d 3 sha1sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -d 3 sha1sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -d 3 sha256sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -d 3 sha256sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -d 3 printf '%s\n') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -d 3 printf '"'"'%s\n'"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -d 3 -- sha1sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -d 3 -- sha1sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -d 3 -- sha256sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -d 3 -- sha256sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -d 3 -- printf '%s\n') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -d 3 -- printf '"'"'%s\n'"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -d 3 -i sha1sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -d 3 -i sha1sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -d 3 -i sha256sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -d 3 -i sha256sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -d 3 -i printf '%s\n' {}) <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -d 3 -i printf '"'"'%s\n'"'"' {}'; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -d 3 -i -- sha1sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -d 3 -i -- sha1sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -d 3 -i -- sha256sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -d 3 -i -- sha256sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -d 3 -i -- printf '%s\n' {}) <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -d 3 -i -- printf '"'"'%s\n'"'"' {}'; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp sha1sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp sha1sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp sha256sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp sha256sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp printf '%s\n') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp printf '"'"'%s\n'"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -- sha1sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -- sha1sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -- sha256sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -- sha256sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -- printf '%s\n') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -- printf '"'"'%s\n'"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -i sha1sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -i sha1sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -i sha256sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -i sha256sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -i printf '%s\n' {}) <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -i printf '"'"'%s\n'"'"' {}'; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -i -- sha1sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -i -- sha1sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -i -- sha256sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -i -- sha256sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -i -- printf '%s\n' {}) <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -i -- printf '"'"'%s\n'"'"' {}'; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -d 3 sha1sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -d 3 sha1sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -d 3 sha256sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -d 3 sha256sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -d 3 printf '%s\n') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -d 3 printf '"'"'%s\n'"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -d 3 -- sha1sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -d 3 -- sha1sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -d 3 -- sha256sum | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -d 3 -- sha256sum | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -d 3 -- printf '%s\n') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -d 3 -- printf '"'"'%s\n'"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -d 3 -i sha1sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -d 3 -i sha1sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -d 3 -i sha256sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -d 3 -i sha256sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -d 3 -i printf '%s\n' {}) <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -d 3 -i printf '"'"'%s\n'"'"' {}'; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -d 3 -i -- sha1sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -d 3 -i -- sha1sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -d 3 -i -- sha256sum {} | tr -s '[ ]*' ' ' | cut -f 2- -d ' ') <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -d 3 -i -- sha256sum {} | tr -s '"'"'[ ]*'"'"' '"'"' '"'"' | cut -f 2- -d '"'"' '"'"''; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n
{ {  diff -q -B -E -Z -d -a -b -w <(printf '%s\n' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -d 3 -i -- printf '%s\n' {}) <(printf '%s\n' "${C[@]}") && printf '%s' "PASS" || printf '%s' "FAIL"; printf ': %s\n' 'printf '"'"'%s\n'"'"' "${C[@]}" | forkrun 2>/dev/null -ks -j 27 -l 1 -t /tmp -d 3 -i -- printf '"'"'%s\n'"'"' {}'; }  | tee -a /tmp/.forkrun.log; } &
(( $(jobs -rp | wc -l) > ${nMax} )) && wait -n

done
